import type { NextPage } from 'next'
import NextLink from 'next/link';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Playground <code className={styles.code}>Next.js</code> for library
        </p>

        <div className={styles.grid}>
          <NextLink href="/design-token" passHref>
          <a className={styles.card}>
            <h2>Design Token &rarr;</h2>
            <p>Build with @wbpesmnt/design-token.</p>
          </a>          
          </NextLink>
          <NextLink href="/stitches/babel" passHref>
          <a className={styles.card}>
            <h2>Stitches Babel &rarr;</h2>
            <p>Build with @wbpesmnt/stitches-babel.</p>
          </a>          
          </NextLink>
          <NextLink href="/stitches/nanobundle" passHref>
          <a className={styles.card}>
            <h2>Stitches Nanobundle &rarr;</h2>
            <p>Build with @wbpesmnt/stitches-nano.</p>
          </a>          
          </NextLink>
          <NextLink href="/stitches/parcel" passHref>
          <a className={styles.card}>
            <h2>Stitches Parcel &rarr;</h2>
            <p>Build with @wbpesmnt/design-parcel.</p>
          </a>          
          </NextLink>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
